### ISSUE TITLE
Repository Naming Bug

### ISSUE THREAD

**Issue by jcho0216** [psh5496/togather#1]
# togather라고 의도하신건가요?

USA Urban Dictionary 레퍼런스에 따르면 togather는 스펠링적으로 틀린 단어입니다.
따라서 togather -> together 해주시면 감사하겠습니다.

<img width="739" alt="Screen Shot 2022-04-01 at 11 56 26 AM" src="https://user-images.githubusercontent.com/67269455/161186366-97470220-6abf-4363-b931-69c53e196eb1.png">

- [ ] togather -> together 수정

**Comment by psh5496** [comment]
to gather = 모으기 위해
라는 뜻으로 의도된 네이밍입니다.
